### ISSUE TITLE
Remove Key form KeyGroup?

### ISSUE THREAD

**Issue by JeremyBYU** [DarthAffe/CUE.NET#31]
First thanks for all your work on this.  Its really great! I have a question about how to turn **off** an LED through keygroups.  I know how to add and remove keys from a keygroup, but only the add functionality seems to work as I expect it.

```
ListKeyGroup keyGroup = new ListKeyGroup(keyboard, keyboard['R'].KeyId);
keyGroup.Brush = new SolidColorBrush(Color.White);
keyboard.Update();
Wait(2);
keyGroup.RemoveKey(keyboard['R'].KeyId);
keyGroup.AddKey(keyboard['T'].KeyId);
```

It seems after this code is executed that R and T are both still lit up white, even though I am attempting to remove R.  Do I have to specifically overwrite the R to black or no color or something?

**Comment by DarthAffe** [comment]
> Do I have to specifically overwrite the R to black or no color or something?

Yes, that's exactly what has to be done.

Currently there are to ways to do so:
- You set the color manually back to black (or whatever color you want). If you have more than one key the following code might be replaced with a new keygroup.

``` C#
keyboard['R'].Led.Color = Color.Black;
```
- (I think this would be the prefered way): You set an explicit background on your keyboard (this has to be done only once):

``` C#
keyboard.Brush = new SolidColorBrush(Color.Black);
```

Unfortunately it's currently impossible to default back to the CUE-settings. This is something we discussed in the corsair-forum - maybe this will be possible in the future.

**Comment by JeremyBYU** [comment]
Awesome, thank you so much!
