### ISSUE TITLE
Add a "Projects using This" Page

### ISSUE THREAD

**Issue by JeremyBYU** [DarthAffe/CUE.NET#32]
Just made a small [app](https://github.com/JeremyBYU/CueMessages) with CUE.net.  Was thinking it would be nice if you had a page that listed open source projects that use CUE.net to demonstrate it abilities. Maybe in the Wiki?

Thanks again!

**Comment by DarthAffe** [comment]
Great idea! I just added the page https://github.com/DarthAffe/CUE.NET/wiki/Projects-using-CUE.NET. Nothing too fancy though :p
