### ISSUE TITLE
Get key coordinates

### ISSUE THREAD

**Issue by RobertBeekman** [DarthAffe/CUE.NET#39]
Hey,

I was wondering if it's at all possible to get the position of a key, preferably in X/Y coordinates?

For Logitech I just made a KeyMap (like so: https://github.com/SpoinkyNL/Artemis/blob/master/Artemis/Artemis/KeyboardProviders/Logitech/Utilities/KeyMap.cs)

I dunno if CUE offers an easier way to do this, if not I don't expect you to go through the boring process of making a map, just wondering :)

**Comment by loganintech** [comment]
There is we already use it SpoinkyNL. Check out the corsair provider it's there. 

Please excuse typos as this was sent from my iPhone

**Comment by RobertBeekman** [comment]
Oh you're right. Sorry for littering your repo DarthAffe :<

**Comment by loganintech** [comment]
Err. We don't use it but the keyboard has an array of keys that each have information about them. X and Y are included.  

Please excuse typos as this was sent from my iPhone

**Comment by DarthAffe** [comment]
That's right,
I don't know which direction you need but you can get the position of a key
http://cue.wyrez.org/class_c_u_e_1_1_n_e_t_1_1_devices_1_1_keyboard_1_1_keys_1_1_corsair_key.html#ac98928919beb938eb7f878b0883992b7

or the key at a position
http://cue.wyrez.org/class_c_u_e_1_1_n_e_t_1_1_devices_1_1_keyboard_1_1_corsair_keyboard.html#ae18a2b2a2c508e52951c23e770d76750
