### ISSUE TITLE
A way to check if the SDK is available without complete initialization 

### ISSUE THREAD

**Issue by RobertBeekman** [DarthAffe/CUE.NET#45]
Hey, I was wondering if it's possible to do this. It would be even better to have a way to check each SDK. 
Something like IsSdkAvailable() , IsKeyboardSdkAvailable() etc. etc. 

I don't think the native C++ sdk provides a feasible way to do this, I could always ask the guys at Corsair, so please let me know what you think :)

**Comment by DarthAffe** [comment]
Well it is possible to check the different 'types' of SDKs by doing a NULL-check. (I'll add methods for this - that's a good hint)
The only 'big' problem right now is, that you need to call initialize first and this will of course fail with a CUEException containing the 'ServerNotFound'-ErrorCode if there is no SDK. The best way right now would be to check for this Exception.
I'll investigate if it's possible to send multiple handshakes, then it would be possible to check for SDK-existence.

**Comment by RobertBeekman** [comment]
Cool, that would be awesome. If there's something that needs to be changed on Corsair's side to make this a lot easier to do, let me know. I can contact the SDK devs in a much more direct route than through forums etc.

**Comment by DarthAffe** [comment]
Could you take a look at this commit if this is what you need?

**Comment by RobertBeekman** [comment]
Looks nice :). From what I can see this won't require calling CueSDK.Initialize and won't interfere with CUE if it was already initialized, is that correct?

Currently I use this, but it's a bit ugly, so this would make it a nice and clean solution

``` cs
private static bool CanInitializeSdk()
{
    // If already initialized, return result right away
    if (CueSDK.ProtocolDetails != null)
        return CueSDK.MouseSDK != null;

    // Else try to enable the SDK
    for (var tries = 0; tries < 9; tries++)
    {
        if (CueSDK.ProtocolDetails != null)
            break;

        try
        {
            CueSDK.Initialize();
        }
        catch (Exception)
        {
            Thread.Sleep(2000);
        }
    }

    if (CueSDK.ProtocolDetails == null)
        return false;
    return CueSDK.MouseSDK != null;
}
```

**Comment by DarthAffe** [comment]
That's right, your code could look like this with the method (The initialization could be done afterwards):

``` C#
private static bool CanInitializeSdk()
{
    for (var tries = 0; tries < 9; tries++)
    {
        if (CueSDK.IsSDKAvailable())
            return true;
        Thread.Sleep(2000);
    }
    return false;
}
```

Just as a note: If you use the MouseSDK to check you will never get true as result if there is a keyboard but no mouse plugged.

**Comment by RobertBeekman** [comment]
Ok nice thanks. I'll try it out as soon as you get the chance to update the Nuget package (No rush :)). As for the method I posted, that method is indeed ment to check only for mice :)

**Comment by DarthAffe** [comment]
oh, in that case you should use CueSDK.IsSDKAvailable(CorsairDeviceType.Mouse) :p
I'm currently testing everything, I'm pretty sure I'll update nuget today.

**Comment by DarthAffe** [comment]
I just updated nuget - I consider this as done now. Feel free to reopen it if there is more I can help with.
