### ISSUE TITLE
Test development-changes with all devices

### ISSUE THREAD

**Issue by DarthAffe** [DarthAffe/CUE.NET#50]
Since I can't test more than my keyboard I'll ask @SpoinkyNL to do this.

The test is quite simple:
Get the latest version of the development branch and run the SimpleDevTest.
It should draw an rainbow on all connected devices (this might look not that good on mouse and headset, mousemat should be ok i think).
The rainbow is lacking red (RemoveRedEffect), should pulse slowly (FlashEffect) and change colors over time (MoveRainbowEffect).

Of course it would be great if you could test it inside artemis too, but since this version contains a huge amount of breaking changes I'm not sure if it can just dropped in without adaptation in artemis.

**Comment by RobertBeekman** [comment]
Hey, the test application crashes on startup because the AbstractCueDevice is calling InitializeLeds(); in the constructor. When creating a CorsairMouse the InitializeLeds(); method is referencing MouseDeviceInfo but that's not set until after the base class has been constructed, resulting in a null reference

**Comment by DarthAffe** [comment]
_facepalm_ I even commented that warning away ...
Please try again with the latest version - it should be fixed

**Comment by RobertBeekman** [comment]
Haha now you know what it ment ^^

It looks pretty good, both mouse and headset update (headset a bit laggy like in #47 but that's a CUE issue)

With the mousemat it seems the bottom LEDs get colored a bit different from the side LEDs, is that intended?

It looks like this: http://i.imgur.com/elYzyGZ.png

For Artemis I wrote some code that maps a brush to the mousemat by reading the pixel colors of the sides (left, bottom and right), maybe that's useful for you too: https://github.com/SpoinkyNL/Artemis/blob/development/Artemis/Artemis/DeviceProviders/Corsair/CorsairMousemats.cs#L56 feel free to rip some stuff out of that if it's any good :)

**EDIT:** Effect stacking works really nice too, great job on that

**Comment by DarthAffe** [comment]
Well, since the mousemat provides coordinates for the LEDs, I'm using them. I don't get why the top and bottom corners aren't vertically aligned, but that's corsairs decision. I think I'll leave it like that.

**Comment by RobertBeekman** [comment]
Ah yeah makes sense to do it with their coordinates, ima do that too, that indeed leaves the implementation with Corsair

**Comment by DarthAffe** [comment]
Since I just released the version I consider this as done for now.
Thanks again for the help :)
