### ISSUE TITLE
[1.0.0] Keyboard DeviceRectangle size

### ISSUE THREAD

**Issue by RobertBeekman** [DarthAffe/CUE.NET#51]
Hey, 

Since the new update calling CueSDK.KeyboardSDK.DeviceRectangle returns a bit of a strange rectangle.
![image](https://cloud.githubusercontent.com/assets/8858506/18419221/1cefa0f6-7856-11e6-904e-978aa1661e1e.png)

As an alternative I can use CueSDK.KeyboardSDK.Brush.RenderedRectangle which seems to be alright, don't know if the old approach is deprecated but figured I'd let you know

**Comment by DarthAffe** [comment]
No, this isn't deprecated and should work as before - I'll investigate this.

**Comment by DarthAffe** [comment]
Sometimes I think I'm stupid ...

**Comment by RobertBeekman** [comment]
Haha mistakes happen! 

Works great though I've already migrated Artemis to the new build :)
