### ISSUE TITLE
Using CUE.NET with CUE2 keyboard keys go to white when calling update()

### ISSUE THREAD

**Issue by kfechter** [DarthAffe/CUE.NET#52]
I have a K70 LUX RGB, and am trying to build a WinForms app using the CUE.NET SDK. I currently have CUE 2 installed.

The following code is how i am setting the keyboard

```
 private CorsairKeyboard keyboardDevice;
if(!CueSDK.IsInitialized)
            {
                CueSDK.Initialize(false); // initialize with non exclusive access
            }

            keyboardDevice = CueSDK.KeyboardSDK;
this.keyboardDevice[CorsairKeyboardLedId.F1].Color = Color.Red;
  this.keyboardDevice.Update(); // update but do not flush
```

Whenever i set the key to red, the entire keyboard goes to white except for the key i set to red.  I only have the keyboard, so not sure what else i can test.

Edit: just calling update without setting any of the other colors also makes the keys go white.

**Comment by DarthAffe** [comment]
I was able to reproduce and fix this error (which was quite a big one). Don't know how I was able to miss that while testing.
Thanks for reporting this!

**Comment by kfechter** [comment]
awesome! absolutely love using this library.

**Comment by DarthAffe** [comment]
FYI: The updated nuget-package is uploaded and should be indexed soon.

**Comment by kfechter** [comment]
awesome!
