### ISSUE TITLE
CUE.NET Does not initialize for some users

### ISSUE THREAD

**Issue by antonpup** [DarthAffe/CUE.NET#55]
Hello, I am experiencing an issue with the library. For some reason, the CUE SDK does not want to initialize for some users, throwing an exception.

```
Exception! Message:System.TypeInitializationException: The type initializer for 'CUE.NET.Native._CUESDK' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: ptr
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at CUE.NET.Native._CUESDK.LoadCUESDK()
   at CUE.NET.Native._CUESDK..cctor()
   --- End of inner exception stack trace ---
   at CUE.NET.Native._CUESDK.CorsairPerformProtocolHandshake()
   at CUE.NET.CueSDK.Initialize(Boolean exclusiveAccess)
   at Aurora.Devices.Corsair.CorsairDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Corsair\CorsairDevice.cs:line 67
```

It works fine for me, even on CUE 2's demo devices. While others cannot even get CUE 1 to work.

Here's an issue that a user posted on my project. https://github.com/antonpup/Aurora/issues/333#issuecomment-272620795

**Comment by DarthAffe** [comment]
Even if I'm not quite sure what the real cause of this issue was I consider this as closed.

**Comment by antonpup** [comment]
If more users bring up this issue, what would you recommend doing to resolve it? Because it's not a one-time case.

**Comment by DarthAffe** [comment]
To be honest I have no idea. I don't even know how the exe i gave him could fix the issue since I just realized that it's builded against a development version of CUE.NET.
I've never heard of this issue before and can't think of anything else than a blocked or missing SDK-dll

**Comment by ThomasAunvik** [comment]
Gotten this same exception with, that was when i was trying to load a 32bit 
iCUE library as a 64bit application.

Also seems like the application is trying to load the 64bit dll instead of the 32bit dll.

But loading just the 32 bit dll to it gets also the same issue with the 32 bit application.

**Comment by RobertBeekman** [comment]
@ThomasAunvik Please open a seperate issue or consider switching to RGB.NET (https://github.com/DarthAffe/RGB.NET)
