### ISSUE TITLE
K95 Platinum lightbar support

### ISSUE THREAD

**Issue by RobertBeekman** [DarthAffe/CUE.NET#57]
Hey,

The new K95 Platinum features a lightbar. I was hoping it woulk show up as a LED zone but it doesn't. The regular keys work out of the box.

This leaves me with colored keys but the lightbar sticking to whatever CUE is setting it to (animations stay in tact)
![image](https://cloud.githubusercontent.com/assets/8858506/24011682/bb00579c-0a7b-11e7-981e-5540306ba4cd.png)

We'll probably have to wait for an SDK update but from what I can gather the dev of [Corsair Effect Engine](http://emily-maxwell.com/?path=cee) found a way to talk to the light bar, she's also using CUE.NET

**Comment by DarthAffe** [comment]
I'm almost 100% sure that Elestriel uses the lightbar directly via USB.  
The one thing that is absolutely breaking for CUE.NET is the fact, that there are no [Id's](https://github.com/DarthAffe/CUE.NET/blob/master/Devices/Generic/Enums/CorsairLedId.cs) defined for the lightbar leds. Therfore it's impossible to address them and we need to wait for an SDK-update. (I won't add USB magic to CUE.NET, maybe to RGB.NET if you want to provide the necessary data and test it :p - I hope I have some more time to work on that stuff again once the next week is over)

**Comment by RobertBeekman** [comment]
Yeah I thought so. I'll ask around to see if a SDK update is around the corner. And of course I'll be happy to help test for RGB.NET again!

**Comment by sll552** [comment]
They recently released an updated SDK see http://forum.corsair.com/v3/showthread.php?t=166450 but I dont know if it includes Lightbar support as there is no changelog for the SDK

**Comment by DarthAffe** [comment]
ohh, nice catch mate - i completely missed on that.
There are 19 new ZoneIds for keyboards so I'm pretty sure that's the lightbar.
I'll implement this asap.

**Comment by RobertBeekman** [comment]
Cool! Let me know if you need testing

Op 17 mrt. 2017 23:21 schreef "DarthAffe" <notifications@github.com>:

**Comment by DarthAffe** [comment]
well, I need some testing :p https://github.com/DarthAffe/CUE.NET/commit/e6719c06a8924cca9afd9491b4c26362e7bf0952 should be enough to make everything work. To test it you can just pull the latest version, compile CUE.NET and run the SimpleDevTest. The lightbar should be part of the animation.

Edit: If everything works I'll release that version (with NuGet and stuff) tomorrow. I need to sleep now ~.~

**Comment by RobertBeekman** [comment]
It worked as soon as I updated to the latest CUE, thanks for the quick response!

**Comment by DarthAffe** [comment]
Release is done and nuget up2date - thanks for the help guys :+1:
