### ISSUE TITLE
Load SDK dll from different location

### ISSUE THREAD

**Issue by sll552** [DarthAffe/CUE.NET#58]
Hi,

i wanted to know if it is possible to tell CUE.NET where to load its native? wrapper from? I am talking about the dll in the "x86" and "x64" folder. 

### Backstory:
I am developing a Plugin for a music player which loads its plugins from a specified folder. And Plugins should only be installed in that folder. But with the current CUE.NET this is not possible because of the loading of this dll that has to reside in the same folder as the main application.
Another problem arises when the Player is started by another program. For example via the "Launch Application" macro in CUE itself. If that happens, CUE.NET searches for the dll in the CUE folder instead of the one of the started application.

PS: I am pretty new to C# (this is my first project) and don`t know much about how the loading of libraries works, so if I'am missing a basic functionality here please point me in the right direction

**Comment by DarthAffe** [comment]
Hi,
right now this isn't possible but it wouldn't be a problem to add the possibility to change that path.
I thought about updating something else this weekend so I'll add this too.

**Comment by sll552** [comment]
Thanks, I am happy to hear that! 
Let me know if you need some external testing, I would be happy to provide that.

**Comment by DarthAffe** [comment]
I just updated the nuget-package - you can modify the way it looks for the dlls now by adding paths to the lists in the CueSDK.
For example:
```C#
CueSDK.PossibleX64NativePaths.Add(@"C:\my\path\x64\CUESDK_2015.dll");
CueSDK.PossibleX86NativePaths.Add(@"C:\my\path\x86\CUESDK_2015.dll");
```

**Comment by sll552** [comment]
Works as expected, thanks again for the fast fix!
