### ISSUE TITLE
Keys which don't exist on a physical device (ie. Macro keys) throws null reference

### ISSUE THREAD

**Issue by logicallysynced** [DarthAffe/CUE.NET#60]
Some users of my app, which implements CUE.NET have been reporting some strange behaviour which I have been unable to replicate myself and I was wondering if you might know where to point me in the right direction.

My app uses CUE.NET to set lighting for Corsair devices across specific keys, however what seems to be happening is when an end-user has a device which is missing certain keys (For example a Strafe RGB does not have physical macro buttons like the K95 RGB), the program throws a null reference error, which my program catches (and reports) but this also locks up CUE.NET so the app must be restarted before Corsair lighting functions again.

Now this has been difficult for me to replicate since I use the CUE2 emulators to test my corsair implementation and for the keyboard, it emulates a K95 RGB which does indeed have macro buttons on it.

Assuming the issue is relating to my code trying to poll/set keys which don't exist on the connected physical device; I think I could potentially work around this by polling the device model using CUE.NET and then avoid setting missing keys programatically, however I was wondering if there is code I'm missing, or can be implemented so if a key is set/polled which doesn't exist on a physical device, if CUE.NET can handle this?

Sorry if I'm making it hard to understand, wording this issue has proven to be a bit more difficult than I expected.. so if you would like me to clarify anything please let me know.

**Comment by DarthAffe** [comment]
I'm pretty sure that a problem on your side (at least if my assumptions on what you're doing are right).
First of all: How are you able to set a key that isn't reported by the keyboard? Are you doing something like this?
```c#
CueSDK.KeyboardSDK[CorsairLedId.Lightbar1].Color = Color.Green;
```
If yes, than the NullReference-Exception is quite obvious. The keyboard doesn't contain the key so the indexer returns null, if you don't null-check the led afterwards setting the color will fail.
If no, I'd need some example on how you're able to do this (this might be a bug on it's own).

The weird thing anyway is, that the exception shouldn't cause any side effects on cue if it's catched.
I tried this with the line above (I only own a K95 so the Lightbar-leds are good to debug such stuff) and the following things worked as expected.
Maybe you're causing some invalid state by having to much/to less in the try-block?

**Comment by logicallysynced** [comment]
I am using a custom KeyMapBrush to set the colors in my library, the implementation goes something like:

    public class KeyMapBrush : AbstractBrush
    {
        private readonly Dictionary<CorsairLedId, Color> _keyMap = new Dictionary<CorsairLedId, Color>();

        public void ClearKeyMap()
        {
            _keyMap.Clear();
        }

        // depending on how you call this method you might need to lock the dictionary in all the methods to prevent weird exceptions due to concurrent accesses from different threads.
        public void CorsairApplyMapKeyLighting(CorsairLedId key, Color col)
        {
            _keyMap[key] = col;
        }

        //CorsairApplyAllKeyLighting
        public void CorsairApplyAllKeyLighting(CorsairLed[] keys, Color col)
        {
            foreach (var key in keys)
                _keyMap[key] = col;
        }

        public CorsairColor CorsairGetColorReference(CorsairLedId key)
        {
            Color color;
            if (_keyMap.TryGetValue(key, out color))
                return color;

            return CorsairColor.Transparent;
        }

        // If you're able to include your logic which key to color here this might get easier than working with the dictionary and stuff.
        protected override CorsairColor GetColorAtPoint(RectangleF rectangle, BrushRenderTarget renderTarget)
        {
            var ledId = renderTarget.LedId;

            Color color;
            if (_keyMap.TryGetValue(ledId, out color))
                return color;

            return CorsairColor.Transparent;
        }
    }

    //Implementation
    public void ApplyMapKeyLighting(string key, Color col, bool clear)
        {
            if (CorsairDeviceKeyboard)
                //Corsairkeyids is a dictionary for translating generic key ids (in my app) to CorsairLedId
                if (Corsairkeyids.ContainsKey(key))
                    _CorsairKeyboardIndvBrush.CorsairApplyMapKeyLighting(Corsairkeyids[key], col);
        }


I'm thinking the lack of null-check like you mentioned might be the issue, it's a pretty bad oversight on my part now that I think about it, haha.

So maybe something such as:
 
    public void ApplyMapKeyLighting(string key, Color col, bool clear)
        {
            if (CorsairDeviceKeyboard)
                if (Corsairkeyids.ContainsKey(key))
                    if (CueSDK.KeyboardSDK[Corsairkeyids[key]].Color != null)
                        _CorsairKeyboardIndvBrush.CorsairApplyMapKeyLighting(Corsairkeyids[key], col);
        }

would be an appropriate fix?

**Comment by DarthAffe** [comment]
Ok, now this gets interesting.
Since you're working with a brush it's impossible that CUE.NET is trying to set a key that doesn't exist. There shouldn't be a need to add null-checks here - even if you add a color for an invalid id in your dictionary it's just ignored since GetColorAtPoint is never called with this id.

I'm a bit at loss right now. The code you posted looks fine (and works for me) so I've no idea why there should be a null-reference-exception.

**Comment by logicallysynced** [comment]
Hmm okay, I'll scan over all the code once more to see if I've missed something or the implementation is wrong. Thanks for your help anyways, if I come across something I'll make sure to make note of it here for you.
