### ISSUE TITLE
Locking the PC stops updates (sometimes)

### ISSUE THREAD

**Issue by Kermittt** [DarthAffe/CUE.NET#61]
I have the keyboard SDK initialized and running in continuous update mode with a handful of keys lit.  (ListLedGroup, SolidColorBrush, custom AbstractBrushEffect) The effect will modify the brush color when the key is pressed.

When the PC is locked the entire keyboard changes to the profile stored on the chip.  This is expected.  However, when the PC is unlocked, the entire keyboard returns to the color configured in CUE and my lighting no longer appears.  Sometimes pressing the keys will bring all my lighting back, but sometimes it never comes back (unclear what the difference is here). I have attempted to call CueSDK.ReInitialize after unlock (via SystemEvents.SessionSwitch event) but it returns the error...
"CUE.NET.Exceptions.WrapperException: 'The previously loaded Keyboard got disconnected.'"
...even if I make sure CueSDK.IsSDKAvailable(CorsairDeviceType.Keyboard) is true first.

Could you please explain the correct way (or add an example) to show how to ensure the lighting applied by CUE.NET will always reappear correctly after a PC is unlocked.

I'm using Win 10, VS 2017, .NET 4.5.

**Comment by DarthAffe** [comment]
Ahh, I'm pretty sure the keyboard really is disconnected (maybe some energy-saving thing). That's a case not properly handled in CUE.NET. I'll look into this and see what I can do to better handle disconnects/reconnects.
Might take a few days, most likely till the weekend.

**Comment by DarthAffe** [comment]
This seems to be a really weird issue. I tried to reproduced the behavior, but wasn't able to do so (using Win 7, this might be the reason).
Even if I unplug the keyboard it's not a problem. As soon as I reconnect it the lighting will continue. 
The only way I was able to prevent it from starting again was by disabling SDK-support in CUE. Even after re-enabling it I had to restart the application. I'm not sure where this comes from but it seems like CUE is killing all SDK-connections and won't allow them to resume if the SDK is disabled.

So far I'd have told to to use Reinitialize to workaround this - and the fact that this doesn't work is surprising. The exception you got (Keyboard got disconnected) says, that CUE doesn't report the keyboard in the list of connected devices anymore. So it seems to be (at least logically) disconnected.

IsSDKAvailable is a bit misleading here. Since you already initialized the SDK the internal state of CUE.NET knows about a keyboard so it assumes that it's still there. I could add a flag to force a real reevaluate but then it would return false which wouldn't really help here.

Besides the energy-saving features or something similar I suspected above I've no idea where this problem might come from. 

As a workaround you could try to wait for 5-10 seconds after getting the SessionSwitch-event and then calling Reinitialize. Maybe the driver needs some time to load the keyboard again.

A second option would be to try-catch the Reinitialize, and if it fails to call IsSDKAvailable(CorsairDeviceType.Keyboard) until it returns true. Then reinitialize again.

**Comment by Kermittt** [comment]
Thanks for the quick response, and sorry for my tardy reply.  Been sidetracked on another project.

I'd like to avoid a timer because that would really be just a workaround and would likely be unreliable.  So here's my attempt at catching the exceptions and retrying the reinitialize.  Note that I'm also switching the UpdateMode to Manual when locked, and back to Continuous when unlocked, in the hope that it might avoid further exceptions in the update routine while locked.
```
        private void SystemEvents_SessionSwitch(object o, SessionSwitchEventArgs e)
        {
            switch (e.Reason)
            {
                case SessionSwitchReason.SessionLock:
                    CueSDK.UpdateMode = UpdateMode.Manual;
                    break;

                case SessionSwitchReason.SessionUnlock:
                    var initialized = false;
                    while (!initialized)
                    {
                        try
                        {
                            if (!CueSDK.IsSDKAvailable(CorsairDeviceType.Keyboard))
                                continue;

                            CueSDK.Reinitialize();
                            initialized = true;
                        }
                        catch (WrapperException ex)
                        {
                            System.Diagnostics.Debug.WriteLine(ex.Message);
                        }
                        catch (CUEException ex)
                        {
                            System.Diagnostics.Debug.WriteLine($"{ex.Error}: {ex.Message}");
                        }

                        if (!initialized)
                            Thread.Sleep(500);
                    }
                    CueSDK.UpdateMode = UpdateMode.Continuous;
                    break;
            }
        }
```
The results from this have been a bit unpredictable but it seems produce these two exceptions...
- CUEException - With an ErrorCode of "ServerNotFound".
- WrapperException - With a Message of "CueSDK isn't initialized."

...in one of these two patterns...
- One CUEException and then infinitely repeating WrapperExceptions.
- One WrapperException then the key lights start updating correctly again.

So this appears to be some kind of timing issue.  I think I'll pull the source today and see if the issue can be caught earlier.

**Comment by Kermittt** [comment]
Looks like I've found a solution to this, and it's actually quite simple.  The problem is that when a CorsairError occurs within Reinitialize you call the static Throw method which clears a bunch of properties and sets IsInitialized = false.  Then you check IsInitialized at the start of Reinitialize and block it from being executed anymore.  The solution is to just leave it in the initialized state and allow the exceptions to keep happening.  Then it will let me repeatedly call Reinitialize until it works.

So the actual code change required is to remove all the property sets in the Throw method, leaving just the "throw new CUEException(error)" line.

I am however noticing that occasionally it will not reset the leds back to the initial state correctly right after unlock, even though later changes to brushes will force them to update.  Will continue to investigate and see if I can make it more reliable.

**Comment by Kermittt** [comment]
Just a couple more minor changes to my reinitialize loop and this now seems to be stable.  After unlock I see the profile color come through for a split second, and then it consistently returns to the colors of the led groups that are applied.

The changes were to reduce the sleep time from 500 to 100, and don't skip the sleep when it has reinitialized successfully.  Updated code is below.

I've branched and modified your code locally for the changes I mentioned in my previous comment, but the changes are so simple it's probably easier for you to update it yourself (and you may want to just remove that Throw method completely).  I'll just run with my modified version for now.  Let me know if you'd like me to commit and issue a pull request.

```
        private void SystemEvents_SessionSwitch(object o, SessionSwitchEventArgs e)
        {
            switch (e.Reason)
            {
                case SessionSwitchReason.SessionLock:
                    CueSDK.UpdateMode = UpdateMode.Manual;
                    break;

                case SessionSwitchReason.SessionUnlock:
                    var initialized = false;
                    while (!initialized)
                    {
                        try
                        {
                            if (!CueSDK.IsSDKAvailable(CorsairDeviceType.Keyboard))
                                continue;

                            CueSDK.Reinitialize();
                            initialized = true;
                        }
                        catch (WrapperException ex)
                        {
                            System.Diagnostics.Debug.WriteLine(ex.Message);
                        }
                        catch (CUEException ex)
                        {
                            System.Diagnostics.Debug.WriteLine($"{ex.Error}: {ex.Message}");
                        }

                        Thread.Sleep(100);
                    }
                    CueSDK.UpdateMode = UpdateMode.Continuous;
                    break;
            }
        }
```

**Comment by DarthAffe** [comment]
That's an interesting catch - https://github.com/DarthAffe/CUE.NET/commit/220953bfe7b0d7e3c3b8f9c2dfb1e21c5113c4c1 should fix the issue, even if I'm still not happy with the initialization/reinitialization in general ...

But even if I'm glad that it works for you now, I still wonder whats the real cause why CUE isn't responding.
