### ISSUE TITLE
HELP NEEDED: How to keep LED changes active after running application?

### ISSUE THREAD

**Issue by finalised** [DarthAffe/CUE.NET#62]
Hey there,
Not an issue, just very lost at the moment.

I'm trying to develop more of a script per se, where I pass in the color I want (going to be via voice) to the application parameters and then change the keyboard LEDs based on that parameter. However, once the program is run, the LEDs change for 0.5s of a second and then goes back to my default profile in Corsair's CUE. 

Is it possible to keep the changes that I've made in my console application after the program has stopped running? 

Any help would be greatly appreciated!

**Comment by RobertBeekman** [comment]
Hi,

When the process closes CUE automatically restores lighting to it's original state. Why don't you keep your application alive until the user closes it?

**Comment by finalised** [comment]
Ahh ok! Just thought I was doing something wrong. I will probably turn the program into a service in that case. Cheers.
