### ISSUE TITLE
UWP Compatibility

### ISSUE THREAD

**Issue by boswelja** [DarthAffe/CUE.NET#66]
I tried to initialize the SDK in a C# UWP project, it threw a WrapperException:
`Exception thrown: 'CUE.NET.Exceptions.WrapperException' in CUE.NET.dll`
My code is as follows: 
```
public MainPage()
        {
            InitializeComponent();
            try
            {
                CueSDK.Initialize();
                Console.WriteLine("Initialized with " + CueSDK.LoadedArchitecture + "-SDK");

                CorsairKeyboard keyboard = CueSDK.KeyboardSDK;
                if (keyboard == null)
                    throw new WrapperException("No keyboard found");

                var ledGroup = new ListLedGroup(keyboard);
                ledGroup.AddLed(CorsairLedId.Lightbar1);
                ledGroup.AddLed(CorsairLedId.Lightbar2);
                ledGroup.AddLed(CorsairLedId.Lightbar3);
                ledGroup.AddLed(CorsairLedId.Lightbar4);
                ledGroup.AddLed(CorsairLedId.Lightbar5);
                ledGroup.AddLed(CorsairLedId.Lightbar6);
                ledGroup.AddLed(CorsairLedId.Lightbar7);
                ledGroup.AddLed(CorsairLedId.Lightbar8);
                ledGroup.AddLed(CorsairLedId.Lightbar9);
                ledGroup.AddLed(CorsairLedId.Lightbar10);
                ledGroup.AddLed(CorsairLedId.Lightbar11);
                ledGroup.AddLed(CorsairLedId.Lightbar12);
                ledGroup.AddLed(CorsairLedId.Lightbar13);
                ledGroup.AddLed(CorsairLedId.Lightbar14);
                ledGroup.AddLed(CorsairLedId.Lightbar15);
                ledGroup.AddLed(CorsairLedId.Lightbar16);
                ledGroup.AddLed(CorsairLedId.Lightbar17);
                ledGroup.AddLed(CorsairLedId.Lightbar18);
                ledGroup.AddLed(CorsairLedId.Lightbar19);

                Console.WriteLine($"{ledGroup.GetLeds().Count()} LEDs in group");
                ledGroup.Brush = new SolidColorBrush((Color)Resources["SystemAccentColor"]);
                ledGroup.Device.Update();
            }
            catch (CUEException ex)
            {
                Console.WriteLine("CUE Exception! ErrorCode: " + Enum.GetName(typeof(CorsairError), ex.Error));
            }
            catch (WrapperException ex)
            {
                Console.WriteLine("Wrapper Exception! Message:" + ex.Message);
            }
        }
```

**Comment by DarthAffe** [comment]
Could you give me the exception message provided by the WrapperException?
Since you seem not to run an console-application the Console.WriteLine in the exception-block won't work, but you could just set a breakpoint in there and copy the message out of the debug-window.

**Comment by boswelja** [comment]
Oh right, can do later on
EDIT: @DarthAffe I can see console output in Visual Studio's output tab

**Comment by boswelja** [comment]
```
Exception thrown: 'CUE.NET.Exceptions.WrapperException' in CUE.NET.dll ("Can't find the CUE-SDK at one of the expected locations:
 'S:\Visual Studio\Projects\test\test\bin\x86\Debug\AppX\x86\CUESDK_2015.dll
S:\Visual Studio\Projects\test\test\bin\x86\Debug\AppX\x86\CUESDK.dll'")	CUE.NET.Exceptions.WrapperException
```
It doesn't appear to be copying the dll to the correct location

**Comment by DarthAffe** [comment]
Are you using the nuget-package? If not the dlls aren't copied on their own. If yes that's somehow weird since there shouldn't be a difference between building a uwp and a normal .net app.

**Comment by boswelja** [comment]
Yes, I'm using the nuget package. The DLLs are copied to `<project dir>\bin\x86\Debug\x86` but it seems the library is looking in the wrong directory?

**Comment by DarthAffe** [comment]
That's interesting. The default behavior is to just look for an "x86/" or "x64/" subfolder. I'm not sure why the application thinks that it's running in an AppX subfolder. Is there maybe some debug-path-configuration for uwp projects?

**Comment by boswelja** [comment]
I don't think there is, other libraries seem to work fine
Sorry for the late response, I apparently didn't hit send on this when I first wrote it

**Comment by DarthAffe** [comment]
Well to be honest I can't see any reason how this could be the fault of the the library. The debug directory is chosen by VS and if it tells wrong paths to nuget there's not too much I can do about that.

Right now I only see two solutions to this problem:
1. If the app isn't working at all (so if it's not a debugger problem) I'm afraid you'd need to copy the dlls into the correct directory by hand or customize the build-target provided by CUE.NET to do so in your special case.

2. I'm not 100% sure how the complete directory-structure of your build-result is but if it works if you use the app directly (so if it's a debugger problem) you could just add your special case to the native-paths:

```C# 
// Execute this two lines before you call CueSDK.Initialize() for the first time.
CueSDK.PossibleX86NativePaths.Add(@"..\x86\CUESDK_2015.dll");
CueSDK.PossibleX64NativePaths.Add(@"..\x64\CUESDK_2015.dll");
```

**Comment by boswelja** [comment]
Ok, I'll try this later.

**Comment by boswelja** [comment]
Sorry for the late reply again, just got some free time.
Even with your code above, it still seems to be checking in a nonexistent AppX folder
```
Exception thrown: 'CUE.NET.Exceptions.WrapperException' in CUE.NET.dll ("Can't find the CUE-SDK at one of the expected locations:
 'S:\Visual Studio\Projects\test\test\bin\x86\Debug\AppX\x86\CUESDK_2015.dll
S:\Visual Studio\Projects\test\test\bin\x86\Debug\AppX\x86\CUESDK.dll
S:\Visual Studio\Projects\test\test\bin\x86\Debug\AppX\x86\CUESDK_2015.dll'")
```
I used both your code above and the following:
```CSharp
CueSDK.PossibleX86NativePaths.Add(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "x86\\CUESDK_2015.dll"));
CueSDK.PossibleX64NativePaths.Add(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "x64\\CUESDK_2015.dll"));
```

**Comment by DarthAffe** [comment]
That's super weird ...
Are you 100% sure that the code I wrote above is correctly executed? I just tested it again and it works fine for me (even though I can't test with UWP). Also in the error message only 3 paths are shown. The first two are the defaults, the second one seems to be the one you added with the basedirectory.

Aside of that I don't see any other option than debugging into the LoadCUESDK to see what he is trying to do with that paths.

**Comment by boswelja** [comment]
How would I know if the code is being executed correctly? It's put right before CueSDK.Initialize(), so I assume it's working.
I'll do more debugging on what the different path variables return, and see if any of them actually point to AppX
